export enum QUIZ_ANSWER_TYPE {
  SINGLE_ANSWER = 'SINGLE_ANSWER',
  MULTIPLE_ANSWER = 'MULTIPLE_ANSWER',
  NO_ANSWER = 'NO_ANSWER',
}
export enum QUIZ_STATUS {
  CANCEL = 'CANCEL', // 取消測驗
  OPEN = 'OPEN',
  FINISH = 'FINISH', // 停止作答
  CLOSE = 'CLOSE', // 結束測驗
  DISCLOSED = 'DISCLOSED', // 老師公佈答案
}
export enum QUIZ_TYPE {
  TRUE_FALSE = 'TRUE_FALSE',
  SINGLE_SELECT = 'SINGLE_SELECT',
  MULTIPLE_SELECT = 'MULTIPLE_SELECT',
  SHORT_ANSWER = 'SHORT_ANSWER',
  RECORD = 'RECORD',
  SINGLE_POLL = 'SINGLE_POLL',
  MULTIPLE_POLL = 'MULTIPLE_POLL',
}
export enum QUIZ_RESPONSE_TYPE {
  TRUE_FALSE_OPTION = 'TRUE_FALSE_OPTION',
  SINGLE_OPTION = 'SINGLE_OPTION',
  MULTIPLE_OPTION = 'MULTIPLE_OPTION',
  TEXT = 'TEXT',
  RECORD = 'RECORD',
}

export enum QUIZ_SOURCE_TYPE {
  LESSON_INSIGHT = 'LESSON_INSIGHT',
  QUIZ_GENERATOR = 'QUIZ_GENERATOR',
  KNSH = 'KNSH',
  MANUAL = 'MANUAL',
}
