export enum QUIZ_TYPE {
  TRUE_FALSE = 'TRUE_FALSE',
  SINGLE_SELECT = 'SINGLE_SELECT',
  MULTIPLE_SELECT = 'MULTIPLE_SELECT',
  RECORD = 'RECORD',
  SHORT_ANSWER = 'SHORT_ANSWER',
  SINGLE_POLL = 'SINGLE_POLL',
  MULTIPLE_POLL = 'MULTIPLE_POLL',
}

export enum QUIZ_ANSWER_RESULT {
  CORRECT = 'CORRECT',
  INCORRECT = 'INCORRECT',
  NO_RESPONSE = 'NO_RESPONSE',
  RESPONSED = 'RESPONSED',
  UNEXPECTED = 'UNEXPECTED',
}

export enum OPTION_TYPE {
  NO_OPTION = 'NO_OPTION',
  TRUE_FALSE = 'TRUE_FALSE',
  NUMBER = 'NUMBER',
  ALPHABET = 'ALPHABET',
}

export enum SOURCE_TYPE {
  QUIZ_GENERATOR = 'QUIZ_GENERATOR',
  MANUAL = 'MANUAL',
  KNSH = 'KNSH',
}
